<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE DIJAK [
<!ELEMENT DIJAK (IME,PRIIMEK,STEVILKA,ULICA,HISTNA_ST,POSTA)>
<!ELEMENT IME (#PCDATA)>
<!ELEMENT PRIIMEK (#PCDATA)>
<!ELEMENT STEVLKA (#PCDATA)>
<!ELEMENT ULICA (#PCDATA)>
<!ELEMENT HISTNA_ST (#PCDATA)>
<!ELEMENT POSTA (#PCDATA)>
]>
<DIJAK>
    <IME>Maj</IME>
    <PRIIMEK>Markez</PRIIMEK>
    <STEVILKA>069</STEVILKA>
    <ULICA>Pod Mostom</ULICA>
    <HISTNA_ST>11c</HISTNA_ST>
    <POSTA>2250 Ptuj</POSTA>
</DIJAK>