<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE NEWSPAPER [

<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT LEAD (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>

<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>

<!ENTITY NEWSPAPER "Vervet Logic Times">
<!ENTITY PUBLISHER "Vervet Logic Press">
<!ENTITY COPYRIGHT "Copyright 1998 Vervet Logic Press">

]>

<NEWSPAPER>&NEWSPAPER;&PUBLISHER;
    <ARTICLE AUTHOR="Samir Đurić">
        <BODY>To je text</BODY>
        <BYLINE>Pozdrav!</BYLINE>
        <HEADLINE>Zakaj so prisli sem?</HEADLINE>
        <LEAD>Iz Nemčije v Mursko Soboto.</LEAD>
        <NOTES>Piši čim več</NOTES>
    </ARTICLE>&COPYRIGHT;
</NEWSPAPER>
