<?xml version="1.0" encoding="UTF-8" ?>


<!DOCTYPE DIJAK [
<!ELEMENT DIJAK (IME,PRIIMEK,STEVILKA,ULICA,HISTNA_ST,POSTA)>
<!ELEMENT IME (#PCDATA)>
<!ELEMENT PRIIMEK (#PCDATA)>
<!ELEMENT STEVILKA (#PCDATA)>
<!ELEMENT ULICA (#PCDATA)>
<!ELEMENT HISTNA_ST (#PCDATA)>
<!ELEMENT POSTA (#PCDATA)>
]>



<DIJAK
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="vaja8.xsd">
    <IME>Maj</IME>
    <PRIIMEK>Markez</PRIIMEK>
    <STEVILKA>1</STEVILKA>
    <ULICA>Opasna ulica</ULICA>
    <HISTNA_ST>2</HISTNA_ST>
    <POSTA>2250 Ptuj</POSTA>
</DIJAK>